### ISSUE TITLE
Support Pop!_OS

### ISSUE THREAD

**Issue by alexrodpas** [cran4linux/rspm#25]
`rpsm::enable() `on Pop!_OS (which is based on ubuntu) returns "Error: OS not supported".

The reason for this is that in Pop!_OS installations, /etc/os-release links to /etc/pop-os/os-release, in which ID=pop (although the file also contains ID_LIKE="ubuntu debian").

Support for Pop!_OS could be done by adding "pop" to the list of supported IDs in os.R, or alternatively, by checking ID_LIKE.

My configuration:
OS: Pop!_OS 22.04 LTS
R version 4.4.0 (2024-04-24) -- "Puppy Cup"

/etc/os-release (/etc/pop-os/os-release) file:
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Comment by Enchufa2** [comment]
Can you please try the branch [feature/25](https://github.com/cran4linux/rspm/tree/feature/25)?

**Comment by alexrodpas** [comment]
Done. Installed the branch [feature/25](https://github.com/cran4linux/rspm/tree/feature/25), and `rpsm::enable()` now works fine.

I'm closing this issue now.

Thanks!

**Comment by Enchufa2** [comment]
Let me close when it's merged, etc. Otherwise, I'll forget. ;-)
