### ISSUE TITLE
Error installing 'units' - missing libudunits2 etc

### ISSUE THREAD

**Issue by micboat** [cran4linux/rspm#29]
Hi thanks for your rspm package. On amazon linux 2023 ec2 instance, I get this error when i enable rspm and try to install units:

Error: Unable to find a match: */libicuuc.so.66 */libicui18n.so.66 */libproj.so.22 */libgdal.so.30 */libgeos_c.so.1 */libudunits2.so.0

i tried rspm::install_sysreqs() but gets the same error

Any idea how I can use rspm to resolve this: I can't install those libraries directly using dnf or yum because aws linux 2023 doesnt support epel.
i reviewed this which led me to your package: https://github.com/amazonlinux/amazon-linux-2023/issues/129

**********linux server info *********************
[root@shiny-app-dev user]# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023.5.20240624"

************R version on server****************
R version 4.3.2 (2023-10-31) -- "Eye Holes"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-amazon-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> rspm::enable()
Tracing function "install.packages" in package "utils"
Tracing function "update.packages" in package "utils"
> install.packages("units")
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.posit.co/all/__linux__/rhel9/latest/src/contrib/units_0.8-5.tar.gz'
Content type 'binary/octet-stream' length 368654 bytes (360 KB)
==================================================
downloaded 360 KB

* installing *binary* package ‘units’ ...
* DONE (units)
Making 'packages.html' ... done

The downloaded source packages are in
	‘/tmp/RtmpdpnYbS/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Inspecting installed packages...
Downloading and installing sysreqs...
Last metadata expiration check: 0:19:49 ago on Tue 25 Jun 2024 12:30:00 PM.
Package salt-3006.8-0.x86_64 is already installed.
No match for argument: */libicuuc.so.66
No match for argument: */libicui18n.so.66
No match for argument: */libproj.so.22
No match for argument: */libgdal.so.30
No match for argument: */libgeos_c.so.1
No match for argument: */libudunits2.so.0
Error: Unable to find a match: */libicuuc.so.66 */libicui18n.so.66 */libproj.so.22 */libgdal.so.30 */libgeos_c.so.1 */libudunits2.so.0
Installation failed! Trying package by package...
Downloading and installing sysreqs for libR...
Last metadata expiration check: 0:20:14 ago on Tue 25 Jun 2024 12:30:00 PM.
Package salt-3006.8-0.x86_64 is already installed.
No match for argument: */libicuuc.so.66
No match for argument: */libicui18n.so.66
Error: Unable to find a match: */libicuuc.so.66 */libicui18n.so.66
Downloading and installing sysreqs for sf...
Last metadata expiration check: 0:20:24 ago on Tue 25 Jun 2024 12:30:00 PM.
No match for argument: */libproj.so.22
No match for argument: */libgdal.so.30
No match for argument: */libgeos_c.so.1
Error: Unable to find a match: */libproj.so.22 */libgdal.so.30 */libgeos_c.so.1
Downloading and installing sysreqs for units...
Last metadata expiration check: 0:20:34 ago on Tue 25 Jun 2024 12:30:00 PM.
No match for argument: */libudunits2.so.0
Error: Unable to find a match: */libudunits2.so.0

**Comment by Enchufa2** [comment]
Thanks for the report. Unfortunately, this package does no magic. ;-) It just relies on the packages available via `dnf` in this case. And moreover library versions for the binary packages provided by Posit should match the ones available in your system repos. So if a dependency is not available, the solution is that AL developers add them to the distribution.

We recently enabled AL 2023 in #27 as per @grantmcdermott request, but as he notes there, AL 2023 is compatible with the RHEL 9 binaries provided by Posit, but many dependencies are not yet available. So there's not much we can do here but redirecting you back to https://github.com/amazonlinux/amazon-linux-2023/issues/129.

**Comment by micboat** [comment]
Thanks for your quick response. Still new in this technical space so trying to figure things out :). I will reach out to AL2023 team.

**Comment by Enchufa2** [comment]
No problem! Closing here then.
