### ISSUE TITLE
CRAN patch release?

### ISSUE THREAD

**Issue by grantmcdermott** [cran4linux/rspm#33]
@Enchufa2 sorry to ask the most annoying question, but is there any chance that a `0.6.1` patch release might make it to CRAN soon? 

As a bit of background, I've convinced my engineering team to incorporate `rspm` into our Docker + deployment pipeline. Overall this has been a big success, since it has enabled smaller builds with less guess work required ahead of time about which dependencies a scientist will need for a particular project. But one or two of our commonly used packages are failing due to the bug that was fixed in #320. I can, of course, suggest the direct `apt install` workaround. But it would be nice to our pipeline work out of the gate with the latest CRAN release of `rspm`, before we announce the revamped logic.

Thanks for considering!

**Comment by Enchufa2** [comment]
On CRAN now.

**Comment by grantmcdermott** [comment]
Excellent, thanks!
